version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    versioning-strategy: increase-if-necessary
    directory: /
    schedule:
      interval: weekly
