name: deviation
description: A diff generation tool and library.
version: 0.0.1
repository: https://github.com/dart-community/deviation

topics:
  - diff
  - patch

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.12.0

dev_dependencies:
  night_raven_insight: ^2.0.0
  test: ^1.24.9
