name: deviation
description: A diff generation tool and library.
version: 0.1.0-wip
repository: https://github.com/dart-community/deviation

topics:
  - diff
  - patch

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  night_raven_insight: ^3.0.0
  test: ^1.25.0
